name = "phperkaigi-2025-try-passkey"
compatibility_date = "2024-12-15"

main = "./.cloudflare/worker.js"

site.bucket = "./.cloudflare/public"

build.command = "bun run build"

compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true
head_sampling_rate = 1

[[d1_databases]]
binding = "DB"
database_name = "phperkaigi-2025-try-passkey"
database_id = "8242adb3-9071-42f2-a3ce-ff48f3ff4d81"

[[kv_namespaces]]
binding = "session"
id = "d3d52a4ffe894141afc893fa83568dff"
preview_id = "ac4cdc1fce6f4a7db3ba320793e45ce3"

[route]
pattern = "phperkaigi-2025-try-passkey.hibiki-cube.dev"
custom_domain = true

[vars]
PUBLIC_RP_NAME ="PhperKaigi 2025 Try Passkey"
PUBLIC_RP_ID = "phperkaigi-2025-try-passkey.hibiki-cube.dev"
PUBLIC_ORIGIN ="https://phperkaigi-2025-try-passkey.hibiki-cube.dev"
